hedgehogqa/haskell-hedgehog

hedgehog.cabal
src/Hedgehog/Example.hs
src/Hedgehog/Internal/Discovery.hs
src/Hedgehog/Internal/Report.hs
src/Hedgehog/Property.hs
src/Hedgehog/Runner.hs
src/Hedgehog/TH.hs
test/test.hs

This significantly improves the test runner, adding coloured output 🌈 and some template haskell code for discovering properties.
The property discovery is a little hacky, but it does deal with multi-line comments, so the following will not be picked up as a property:
```hs
{-
prop_foo =
not done yet
-}
```
The failure output pulls in the source code of the property and annotates it with the generated test data, as well as "calling out" which of your propositions actually failed. I can imagine this will be useful when you have a `conjoin` like thing with many possible ways in which you can fail:
The source code annotation relies on the GHC 8.0 `CallStack` API, so I'm going to need to figure out something to do as a stop gap for use in GHC 7.10. I'll probably just go back to printing the …

Coloured reporting and Template Haskell runner

---

hedgehog.cabal
src/Hedgehog/Internal/Discovery.hs
src/Hedgehog/Internal/Report.hs
src/Hedgehog/Internal/Source.hs
src/Hedgehog/Property.hs
src/Hedgehog/Runner.hs

This adds a fallback renderer for 7.10 because we can't get call stack information until GHC 8.0:
It's not too bad, certainly not as busy as the 8.0 output, but not as useful for diagnosing a failure either. This is also the output you would get in 8.0 now if the test runner failed to locate a file where an input supposedly came from.
The `Hedgehog.Internal.Source` module re-exports the parts of the `GHC.Stack` API that we need, and shims enough of it for 7.10 so we don't need CPP in the rest of the project.

Add fallback rendering for 7.10

---

hedgehog-example/test/Test/Example/Basic.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Property.hs

This adds a top level module so people don't need to hunt for imports, it also has some placeholder doc which I will elaborate on before release.
I've also twiddled the names, gone from `ensure` back to `assert` and `forAll` is now `given`. I'd be interested in any feedback on this. I'm not particularly concerned with being familiar to QuickCheck users anymore given how different this library is now, so I'm mainly interested in how you think properties read using these names for things.

Add top level Hedgehog module

---

hedgehog-example/test/Test/Example/Basic.hs
hedgehog-example/test/Test/Example/STLC.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/Show.hs

This was one of the last things left to do before a Hackage release, the test runner now shows the current status of a test while it is running/shrinking:

Show current test status while running/shrinking

---

README.md
hedgehog-example/test/Test/Example/Basic.hs
hedgehog-example/test/Test/Example/Resource.hs
hedgehog-example/test/Test/Example/STLC.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/TH.hs
hedgehog/test/Test/Hedgehog/Text.hs

This adds a type `Group` which is a named collection of properties.
`checkConcurrent` and `checkSequential` are now regular functions which can execute the property tests in a `Group`. The Template Haskell property discovery is now just a single function `discover` which returns a `Group`.
Running tests with automatic discovery now looks like this:
```hs
tests :: IO Bool
tests =
checkConcurrent $$(discover)
```
But now, if you prefer to avoid macros, you can specify the group of properties to run manually instead:
```hs
tests :: IO Bool
tests =
checkConcurrent $ Group "Test.Example" [
("prop_reverse", prop_reverse)
]
```

Make it easier to use Hedgehog without Template Haskell

---

hedgehog/src/Hedgehog/Gen.hs

I spent a while looking for this function, and eventually found #34 and felt silly when I realized you can just use `pure` for this. So I figured since at least two of us have made this mistake so far, it'd be good to leave some kind of reminder in the documentation.
I propose adding an alias called `constant`, with a note explaining that it is equivalent to `pure`.
It didn't quite fit neatly into any of the sections, but I put it under "Choice" because you can think of it as a specialization of `element` with a single value, which I also point out in the documentation.

add Gen.constant

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs

This adds `GroupName` and `PropertyName` to the `Hedgehog` module; these types are important to have when you're constructing groups explicitly instead of using TH.
I also added `Semigroup` instances because I found myself wanting to append text onto property names.

Expose GroupName and PropertyName

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

If you had a large number of tests before, the default concurrent runner could end up off the screen. Now we only show tests that are running or have been run, with just a single line dedicated to the tests which are yet to come.
This should partially address https://github.com/hedgehogqa/haskell-hedgehog/issues/51
The next thing is to add a quiet mode which users can configure if they prefer, which just displays the number of tests passed at the end of the execution, and any failures which occurred. This may even be preferable on CI servers, even though the current system does handle non-tty stdout correctly.

Concurrent runner doesn't display tests which aren't running

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Config.hs
hedgehog/src/Hedgehog/Internal/Queue.hs
hedgehog/src/Hedgehog/Internal/Region.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

This resolves https://github.com/hedgehogqa/haskell-hedgehog/issues/51 by adding an optional quieter test runner.
It can be activated in code using `checkGroup` or by setting the environment variable `HEDGEHOG_VERBOSITY=0`.
Ideally the ANSI color configuration and test runner verbosity could also be set using a user config file, but that's for another PR.
Some screenshots:
/cc @chris-martin

Add quiet test runner

---

hedgehog-example/test/Test/Example/STLC.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/test/Test/Hedgehog/Text.hs

I think it's technically more correct to say that we're running the tests in parallel, as the goal is improved throughput, and there is no non-deterministic control flow.
I thought I would rename this before release as there is already a breaking change in this area due to the introduction of `$$(discover)`

Rename checkConcurrent -> checkParallel

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs

It was only for 7.10 anyway, and it turns out that some type level hackery can't be used with a `Typeable` constraint. This, in conjunction with a custom render function, will allow those situations to work properly.

Remove use of Typeable / allow custom render function

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs

This implements the `annotate` feature as discussed in https://github.com/hedgehogqa/haskell-hedgehog/pull/60 (so I will close that one)

Add 'annotate' function for annotating source code with additional info

---

CHANGELOG.md
hedgehog/CHANGELOG.md
hedgehog/hedgehog.cabal

Hackage complained when I uploaded a package candidate without a changelog, I though this was a good idea in any case.

Add changelog

---

hedgehog-example/test/Test/Example/Basic.hs
hedgehog/src/Hedgehog/Gen.hs

This adds some generators for various character sets, and a property test which fails with the current version of `text` on Hackage as an example usage.
The test was inspired by https://github.com/bos/text/issues/176 and the generator choices are similar to the ones which have recently been added to QuickCheck using `Arbitrary` instances for `Char` newtypes.

Add ascii/latin1/unicode character generators

---

hedgehog/src/Hedgehog/Gen.hs

I came across this while porting https://github.com/hedgehogqa/haskell-hedgehog/pull/73/ to the F# version: https://github.com/hedgehogqa/fsharp-hedgehog/pull/96/.
See also:
- https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates
- https://referencesource.microsoft.com/#mscorlib/system/char.cs,913

Use (DFFF)16/(57343)10 as the low surrogate

---

hedgehog-example/test/Test/Example/Resource.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Distributive.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Tree.hs

Perhaps adding a type class here is overkill, but I think we need the type family instances to make it manageable to use, so :man_shrugging: 
I think I'm going to go for it and see what happens.

Distributive class for pulling a transformer out to the top level

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/test/Test/Example/Roundtrip.hs
hedgehog/src/Hedgehog/Internal/Tripping.hs

I hope @thumphries doesn't mind, I turned his [blog post](http://teh.id.au/posts/2017/06/07/round-trip-property/) in to an example.
While I was doing so I noticed that the `tripping` function could be improved a bit, I added an output with the intermediate value:
I understand that the intermediate value may not always be something supporting `Show` and could potentially be large, but I think this behaviour is a nice default. I think longer term we should have a `trippingWith` function which is a bit more configurable, but this is ok for now.

Add roundtrip test from Tim's blog post

---

hedgehog/src/Hedgehog/Internal/State.hs

Found this while using the new state machine stuff, if you have two different return types then you can end up with a type error while shrinking. This fixes that issue.

Types are a thing

---

hedgehog-example/test/Test/Example/References.hs
hedgehog-example/test/Test/Example/Registry.hs
hedgehog-example/test/test.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Opaque.hs
hedgehog/src/Hedgehog/Internal/State.hs

This adds an extra data type for working with state machine variables. It frees the user from having to derive `Eq`, `Ord`, `Show` by hand for data structures which contain variables.
This PR also adds an extra argument to the `Ensure` callback which is the previous state. Having the previous and the current state can sometimes be useful when writing post-conditions.

Easier to use variables for state machine testing

---

hedgehog-example/test/Test/Example/Exception.hs
hedgehog-example/test/test.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Exception.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Queue.hs
hedgehog/src/Hedgehog/Internal/Region.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

This adds the `evaluate :: a -> Test m a` function which will evaluate its argument and fail the test if doing so throws an exception. I have updated `assert` and `(===)` to both make use of this, so exceptions thrown from pure code should now be reported properly.
This fixes #57 and addresses an issue @tmcdonell raised IRL.
Sorry for the potentially misleading title @erikd, this does not solve #84.

Better support for tests which throw exceptions

---

hedgehog-example/test/Test/Example/References.hs
hedgehog-example/test/Test/Example/Registry.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Region.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/State.hs

This adds supports for parallel state machine testing. The shrinking could be vastly improved but it's at least a start.
I have rejigged some of the monad transformers because it now becomes useful to have a pure test which can be used in the post-condition for state machines.

Parallel state machine testing

---

hedgehog/src/Hedgehog/Internal/Gen.hs

This changes `Gen.sample` to return a single result instead of a list. Users can always use `replicateM 10 Gen.sample` if they want the old behaviour. /cc @erikd
I also changed the sampling functions to work over `Gen` instead of `GenT` because otherwise users would need to say `Gen.sample (Gen.lift gen)` if they wanted to sample vanilla generators, which I think is going to be the common case.

Gen.sample now only gives a single result back

---

hedgehog/src/Hedgehog/Internal/Config.hs
hedgehog/src/Hedgehog/Internal/Discovery.hs
hedgehog/src/Hedgehog/Internal/Distributive.hs
hedgehog/src/Hedgehog/Internal/Exception.hs
hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/HTraversable.hs
hedgehog/src/Hedgehog/Internal/Opaque.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Queue.hs
hedgehog/src/Hedgehog/Internal/Range.hs
hedgehog/src/Hedgehog/Internal/Region.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/Seed.hs
hedgehog/src/Hedgehog/Internal/Show.hs
hedgehog/src/Hedgehog/Internal/Shrink.hs
hedgehog/src/Hedgehog/Internal/Source.hs
hedgehog/src/Hedgehog/Internal/State.hs
hedgehog/src/Hedgehog/Internal/TH.hs
hedgehog/src/Hedgehog/Internal/Tree.hs
hedgehog/src/Hedgehog/Internal/Tripping.hs

At the moment, clicking around on Haddock references to the public API leads you into the internal modules.
The `not-home` option makes Haddock link to the public API for publicly exported identifiers. It still links to the internals for things that aren't otherwise exported.

Use haddock not-home option for internals

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/test/Test/Example/QuickCheck.hs
hedgehog-example/test/test.hs
hedgehog-quickcheck/CHANGELOG.md
hedgehog-quickcheck/LICENSE
hedgehog-quickcheck/README.md
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog-quickcheck/src/Hedgehog/Gen/QuickCheck.hs
hedgehog-quickcheck/src/Test/QuickCheck/Hedgehog.hs
hedgehog/hedgehog.cabal

This allows the use of QuickCheck generators and Arbitrary instances in Hedgehog, and also the use of Hedgehog generators inside QuickCheck.
Unfortunately I can't think of a way to get shrinking when using Hedgehog generators inside QuickCheck, but the other way is possible.

Support for using QuickCheck generators in Hedgehog and vice versa

---

hedgehog/src/Hedgehog/Internal/Seed.hs

See mixGamma http://gee.cs.oswego.edu/dl/papers/oopsla14.pdf on page 13.
Also see jane streets implementation for comparison https://github.com/janestreet/core_kernel/blob/master/src/splittable_random.ml#L87.
@jystic On a side note, there is a dedicated place for people who write bit masks in decimal, I dearly hope you have someone else to blame.

Correct mixGamma oddness check.

---

hedgehog/src/Hedgehog/Internal/Queue.hs

This clears up some warning text.

only invoke setNumCapabilities when using the -threaded runtime

---

hedgehog/hedgehog.cabal

changelog: https://hackage.haskell.org/package/ansi-terminal-0.8.0.1/changelog

Bump dependency on ansi-terminal

---

.travis.yml

We should prepare for the quickly approaching GHC 8.4 release. This adds the pre-release version to travis, but as an allowed failure for now.

Add GHC 8.4.1 as an allowed failure to Travis

---

hedgehog/hedgehog.cabal

Conditional dependency on `semigroups` causes some problems for tools that don't know now to deal with `if`s in cabal files. I can't build `hegdgehog` on the `ghc7102` or `ghc7103` package sets, because the tools don't know how to account for the conditional dependency. It's okay to just always depend on semigroups - see https://qfpl.io/posts/semigroups/
Please [squash this PR](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) when you merge it :)

Depend on `semigroups`

---

.gitignore
cabal.project

This lets you build all three packages from the top level with `cabal new-build all`
I've also added the new-build artifacts to the .gitignore

Cabal.project

---

.travis.yml
hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/State.hs

Here's some CPP to support transformers 0.4. This should help some users using GHC 7.10 since transformers 0.4 is a boot library on that version.

Support transformers 0.4

---

hedgehog/hedgehog.cabal

- `template-haskell` is at `2.13` in GHC 8.4
- `resourcet` `1.2.0` was released the other day
We should be good for 8.4 after this, will aim for a point release
@nhibberd @gwils

Bump upper bounds for template-haskell and resourcet

---

hedgehog/src/Hedgehog/Internal/Gen.hs

I haven't fully tested this, but I think this should work, right?
https://github.com/hedgehogqa/haskell-hedgehog/issues/153

unicode no longer generates noncharacters

---

hedgehog-example/src/Test/Example/Basic.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs

Hi @thumphries, @jystic, here is a proposal for a `/==` operator. 
Hmm I can see that stylish-haskell has made the diff larger than it should. Do you have any specific formatting rules?

Added a /== operator to express that 2 values must be different

---

hedgehog/src/Hedgehog/Internal/HTraversable.hs
hedgehog/src/Hedgehog/Internal/Range.hs

I am open to suggestions re. style.  I just hacked in what would have helped me.  (-:
(That's one commit; the other is just cut & paste from #41.)

Add some documentation bits.

---

hedgehog/hedgehog.cabal

so that async 2.2.* can be used.

Move async and lifted-async bounds

---

hedgehog/src/Hedgehog/Internal/Gen.hs

This uses the technique suggested in [Equational Reasoning at Scale](http://www.haskellforall.com/2014/07/equational-reasoning-at-scale.html) to provide a `Monoid` instance for `GenT`. This was motivated by more than just theoretical concerns. At work, I was recently in a situation where I needed to flatten a list of generators like this:
flatten :: [Gen ByteString] -> Gen ByteString
With the instances provided by this PR, `flatten` is just `mconcat`. I've written these instances so that they should be compatible with all phases Semigroup-Monoid-Proposal that are represented by GHC 8.4 and lower.

Add Semigroup and Monoid instances for GenT that lift the inner Monoid

---

hedgehog/hedgehog.cabal

This will compile ok when concurrent-output also increases its upper bound.

Bump upper bound for exceptions to 0.11

---

.travis.yml

Ghc 8.4 has now had an official release so the build should succeed.

.travis.yml: DIsallow failures with ghc 8.4

---

hedgehog/src/Hedgehog/Internal/Discovery.hs

Exceptions thrown by `readDeclaration` make it impossible to write properties inside GHCi. This PR just catches them.
I think this sufficiently addresses #105, the @chris-martin example from that issue now works.
```
λ> import Hedgehog
λ> import qualified Hedgehog.Gen as Gen
λ> import qualified Hedgehog.Range as Range
λ> check $ property $ forAll (Gen.integral $ Range.exponential 1 1024) >>= \x -> x + 1 === x
✗ <interactive> failed after 1 test.
forAll0 =
1
This failure can be reproduced by running:
> recheck (Size 0) (Seed 7634626840477011566 (-6948853007075827919)) <property>
False
```

Catch readFile exceptions on the repl

---

.travis.yml
cabal.project
hedgehog-dieharder/LICENSE
hedgehog-dieharder/hedgehog-dieharder.cabal
hedgehog-dieharder/test/Dieharder.hs
hedgehog/src/Hedgehog/Internal/Seed.hs
hedgehog/test/Test/Hedgehog/Text.hs

Currently, most DieHarder tests are failing. This resolves #125 by passing all DieHarder tests :tada: :balloon: 
/cc @jystic @markhibberd @nhibberd @thumphries, not necessarily in this order!

Pass DieHarder statistical/randomness tests

---

hedgehog/src/Hedgehog/Internal/Seed.hs

`Int32` is only used on 32 bit platforms and `Int64` is only used on 64 bit platforms so tweak the `CPP` stuff so that there are no warnings (mafia made me do this).
Built this in 32 bit Debian as a test. Zero warnings. Tests passed.

Seed: Fix compiler warning

---

hedgehog/src/Hedgehog/Internal/Seed.hs

Resolves https://github.com/hedgehogqa/haskell-hedgehog/issues/191 ― See https://github.com/hedgehogqa/haskell-hedgehog/issues/191#issuecomment-391209131 ― ✔ Passes all dieharder tests. :neckbeard:
---
```
$ dieharder-input | dieharder -a -g 200
#=============================================================================#
#=============================================================================#
rng_name    |rands/second|   Seed   |
stdin_input_raw|  3.00e+07  |2424813648|
#=============================================================================#
test_name   |ntup| tsamples |psamples|  p-value |Assessment
#=============================================================================#
diehard_birthdays|   0|       100|     100|0.88800885|  PASSED  
diehard_operm5|   0| …
```

 Avoid weak gamma values in Hedgehog.Internal.Seed

---

hedgehog/hedgehog.cabal
hedgehog/test/Test/Hedgehog/Seed.hs
hedgehog/test/test.hs

We were missing the test part in Haskell, which is pretty [similar to what we did in F#](https://github.com/hedgehogqa/fsharp-hedgehog/pull/161/commits/1746ddffd643a273662e277d50bec7f5bc024510). See Melissa E. O'Neill's post with title [Bugs in SplitMix(es)](http://www.pcg-random.org/posts/bugs-in-splitmix.html), #191, and 39b15b9b4d147f6001984c4b7edab00878269da7, for more context.
/cc @jystic @thumphries

Add tests to verify that our SplitMix/Seed avoids pathological γ-values

---

hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

There are two issues on Windows:
1. ```
<stdout>: commitBuffer: invalid argument (invalid character)
```
2. ```
ΓöüΓöüΓöü Q49343774 ΓöüΓöüΓöü
Γ£ô prop_reverse passed 100 tests.
Γ£ô 1 succeeded.
True
```
---
- Issue `1` is annoying—it terminates the process and [breaks CIs](https://github.com/input-output-hk/cardano-sl/commit/315a264bf304fc62d7786091a44363badd29c1c3) [and stuff like that](https://github.com/hedgehogqa/haskell-hedgehog/issues/178)
- Issue `2` can either be addressed by [cooking some al dente](https://github.com/commercialhaskell/stack/blob/dc04605ea1a6648f8e1429a0a34886fcbf53b0cc/src/Stack/Build.hs#L296-L341) or by just typing `chcp 65001`
---
Resolves #110 by fixing issue `1`.

Set stdout/stderr encoding to UTF-8 on Windows

---

.travis.yml
hedgehog-dieharder/hedgehog-dieharder.cabal
hedgehog-example/hedgehog-example.cabal
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog/hedgehog.cabal

Leave resourcet in hedgehog-example for now, since
it does not compile with newer resourcet
With these bounds in place, we should be able to build on GHC 8.6.1 once lifted-async has updated their base upper bound. When that happens I'll add 8.6.1 to the travis build.

Update upper bounds for many dependencies

---

hedgehog/hedgehog.cabal

I've already made the metadata revision corresponding to this pull request, so there's no need for a new release.

Bump ansi-terminal upper bound

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Discovery.hs
hedgehog/src/Hedgehog/Internal/TH.hs

We are using this change to have specific sets of properties, for example golden tests, with their own prefix.

Expose discoverPrefix to find prefixed properties

---

hedgehog/src/Hedgehog/Internal/Gen.hs

'enumBounded' is partial in some cases. Usually you actually want something like `Gen.linear minBound maxBound` or similar. The error message is pretty inscrutable when you mess it up (no source locations), so I think a cautionary message is worthwhile.
Bikeshed on wording welcome

Add note about enumBounded

---

hedgehog/src/Hedgehog/Internal/State.hs

`no valid interleaving` as an error message leaves a bit to be desired. Without seeing what the concrete outputs were, it can be hard to figure out where the race condition(s) might be.
With this change, we show the outputs each Concrete Var got during the parallel execution.
The biggest downside is that all output types must now have `Show` instance, so it's unfortunately a breaking change.

Show output variables when parallel state machine testing fails to linearise

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Property.hs

Some folks might use generators in do notation with a partial pattern match, this won't work with GHC 8.6 without a MonadFail instance.
Although it's probably not the best practice, I would imagine that discarding the non-matching sample is better than throwing an exception.
~~Other that that I just turned on a few warnings and fixed them.~~

Add MonadFail instances where appropriate

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/test/test.hs

And actually use it in the Hedhehog tests.
Closes: https://github.com/hedgehogqa/haskell-hedgehog/issues/97
@thumphries @jystic @nhibberd

Add a runTests function

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/src/Test/Example/Resource.hs

Relax bound, and use `hoist` to work with `MonadUnliftIO`.
See also: discussion about resourcet in #252 .

hedgehog-example: relax resourcet to < 1.3

---

hedgehog-quickcheck/hedgehog-quickcheck.cabal

I suggest also making this change as a hackage metadata revision to the most recent release of hedgehog-quickcheck (I'm happy to do so if you'd like)

Bump QuickCheck upper bound

---

hedgehog-example/src/Test/Example/Resource.hs
hedgehog/src/Hedgehog/Internal/Property.hs

Make `PropertyT` an instance of `MonadResource` simplifies writing tests that use the functions with a `MonadResource` constraint. See the changed example for instance.

Make 'PropertyT' an instance of 'MonadResource'

---

hedgehog/src/Hedgehog/Internal/Property.hs

Add `MonadFail` instance for `PropertyT` so users can write the following tests
property $ do
Just val <- lookupUnderTest
assertSomeProperties val
The above test will produce a test failure when `lookupUnderTest` returns `Nothing`.
We build on the `MonadFail` instances for `TestT` provided by #233.

Add 'MonadFail' instance for 'PropertyT'

---

hedgehog-example/src/Test/Example/Basic.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Tripping.hs

This PR adds 4 functions, that have similar behaviour to === and /==, except they correspond to different relations.
(<==) ~> (<=)
(>==) ~> (>=)
(>>>) ~> (>)
(<<<) ~> (<)
As for naming, I tried to keep them to three characters while making sure their names didn't conflict with anything popular.
The reason I wanted this is that I was doing some numerical computations and wanted to test that the result of a computation was less than or equal to a particular value.

add relation stuff ala === and /==

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Main.hs
hedgehog/test/test.hs

`defaultMain` seems to be the convention in many Haskell packages which produce a command line program, so I think it will be less surprising / something people look for:
- [Cabal](http://hackage.haskell.org/package/Cabal-2.4.1.0/docs/Distribution-Simple.html#v:defaultMain)
- [Yesod](http://hackage.haskell.org/package/yesod-1.6.0/docs/Yesod-Default-Main.html)
- [Criterion](http://hackage.haskell.org/package/criterion-1.5.4.0/docs/Criterion-Main.html)
- [Tasty](http://hackage.haskell.org/package/tasty-1.2.1/docs/Test-Tasty.html#v:defaultMain)
- Many more...
Ideally we'll move to something better than `[IO Bool] -> IO ()` in the future, maybe with verbosity / color controls and parallel test running across test modules.

Rename Hedgehog.runTests -> Hedgehog.Main.defaultMain

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/src/Test/Example/Coverage.hs
hedgehog-example/test/test.hs
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

This adds `label` and `collect` similar to QuickChecks coverage support. This is achieved using an extra constructor on the existing `Log` type, which collects `Label`s. You could similarly add a `Class` constructor to implement QuickChecks `classify` and I will happily make a PR for that too if this approach seems reasonable.
Display of labels could also use source information to be printed under the `label` command, similar to `annotate`s existing behaviour. If this gets merged I can add that and the other extension mentioned above as issues.

Add labelling of test cases

---

hedgehog-quickcheck/src/Test/QuickCheck/Hedgehog.hs
hedgehog-test-laws/test/test.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/State.hs
hedgehog/src/Hedgehog/Internal/Tree.hs
hedgehog/test/Test/Hedgehog/Zip.hs
hedgehog/test/test.hs

This changes the `Applicative` instance for `GenT` so that it [zips](https://github.com/well-typed/integrated-shrinking/blob/master/src/UsingHedgehog.hs#L255-L277) the tree rather than binding it. This means that a generator like `(,) <$> genA <*> genB` will be able to alternate between shrinking `genA` and `genB` rather than doing one first and then the other.
An example shrink tree using a zipping approach vs just using `(<*>) = ap`:
I had it like this originally and changed it because it broke the law `<*> = 
ap`, but I'm not sure this is that important as the `Monad` instance for `GenT` is already unlawful.
[Haxl](https://simonmar.github.io/bib/papers/haxl-icfp14.pdf) also uses an unlawful `Applicative` instance for basically the same reason. This was the motivation for …

 Change Applicative GenT to use zipping

---

.appveyor.yml
.travis.yml
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Config.hs
hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/Source.hs

I keep running up against compatibility issues, and I think it's old enough now.
We'll still have support for GHC 8.01, which is three years old now.

Drop support for GHC 7.10

---

hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/State.hs
hedgehog/src/Hedgehog/Internal/Tree.hs
hedgehog/test/Test/Hedgehog/Filter.hs

This implements @edsko's ideas from #281. I made the default `filter` the "ideal" one presented last in that issue, it just requires that the base `Monad` is `Identity` which I would expect to be the case 100% of the time when using `filter`. The faster one is `filterT` and can be used with any base `Monad`, I'm not sure if this should even be included. It is indeed faster but i'm not sure if that's so important?

Fix filter shrinking bug #281

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/State.hs
hedgehog/src/Hedgehog/Internal/Tree.hs
hedgehog/test/Test/Hedgehog/Applicative.hs
hedgehog/test/Test/Hedgehog/Filter.hs
hedgehog/test/test.hs

Running a `StateT` on the inside of `GenT` doesn't work properly with the new applicative implementation, so we `distributeT` to move it to the outside before running it.
It has to be on the inside, because otherwise it's not a `MonadGen`, due to the new list shrinking code. It does seem kind of odd that I can't make it work on the outside, it must be possible.

Fixed state machine duplicate Vars when shrinking

---

hedgehog-example/src/Test/Example/Resource.hs
hedgehog/src/Hedgehog/Internal/Property.hs

As noted in https://github.com/hedgehogqa/haskell-hedgehog/issues/284, the documentation for `Hedgehog.test` is wrong. This updates that and also adds an example for observing when certain actions are run during the testing and shrinking process for those who are interested.

Document the use case for 'test' and improve 'ResourceT' example.

---

hedgehog/src/Hedgehog/Main.hs

Makes this go away (trimmed to fit into 80 chars width):
```
..\hedgehog\src\Hedgehog\Main.hs:12:1: warning: [-Wunused-imports]
The import of `hSetEncoding, utf8'
from module `System.IO' is redundant
|
12 | import           System.IO (BufferMode (LineBuffering), hSetBuffering, hSetEncoding, std...
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Fix -Wunused-imports warning on Windows/MinGW

---

hedgehog-example/src/Test/Example/Coverage.hs
hedgehog/src/Hedgehog/Internal/Report.hs

This PR adds unicode histograms / percentage bars to the new labelling / coverage system. Not sure if I have quite the right balance yet, but time will tell.
For labels with coverage requirements, the minimum required coverage is shown on the right hand side of the histogram, along with a tick or a cross indicating whether we met the requirement. We also highlight visually (with red dots) the additional coverage required to make it to the requirement, not sure if I like this yet but we'll give it go.
Shame :australia: :greece: haven't won any world cups :cry:

Add histograms to labels / coverage

---

CHANGELOG.md
README.md
hedgehog-quickcheck/CHANGELOG.md

Also fixed up the AppVeyor account to be `hedgehogqa`, didn't realize it wasn't registered as `jystic`

Renamed @jystic -> @jacobstanley

---

CHANGELOG.md
README.md
hedgehog/hedgehog.cabal

Should have really done that earlier :D
The `CHANGELOG.md` fixups didn't make it to the hackage release unfortunately, will have to wait until next time. Shame the changelog can't be modified after the fact like version bounds. Maybe via `Upload Documentation` idk.

Fixups after previewing the package candidate

---

STYLE_GUIDE.md

I mined a recent PR for most of these so fair to say there is plenty of adjustment required.
But it is easier to have this discussion here.

Add first cut of style guide

---

hedgehog/src/Hedgehog/Internal/Gen.hs

Rather than filter unicodeAll, we can construct the set of characters we want.
This has the added benefit of removing the `GenBase m ~ Identity` constraint.

Stop using filter to define unicode.

---

hedgehog/src/Hedgehog/Internal/Report.hs

Fixes #306.
Adds the location of the failed assertion (taken from the `Span` value of the failure report). Example output:
```
✗ <interactive> failed at test/Test/Hedgehog/Applicative.hs:91:11
after 1 test.
┏━━ test/Test/Hedgehog/Applicative.hs ━━━
69 ┃ ...
```
This enables editors to more easily parse the location of failed test assertions, and provide links/jump functionality. This has been tested with Emacs.

Include location of failed assertion in report

---

.appveyor.yml
.travis.yml
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs

---
Edit (@moodmosaic): Resolves #317

Make it build with gch 8.8 and add ghc 8.8 travis build

---

hedgehog/hedgehog.cabal

https://github.com/commercialhaskell/stackage/issues/4798
The changes implemented in `ansi-terminal-0.10` do not affect this package.

Allow ansi-terminal 0.10

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/src/Test/Example/Confidence.hs
hedgehog-example/test/test.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/test/Test/Hedgehog/Confidence.hs
hedgehog/test/test.hs

This PR adds ability to be able to statistically verify that a result is correct. It does not _yet_ add the ability to cancel running tests if they can never reach the specified coverage.

Statistically verify result

---

hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Tree.hs

I believe it is possible to write a lawful `MonadBaseControl` instance
for `CofreeT` (see [this proof](https://github.com/ekmett/free/issues/193#issuecomment-535173061)), and therefore also for the `TreeT`, `GenT`, and
`PropertyT` types in this package. I can't say for sure whether it
"makes sense", but hey, maybe it does.

Add a MonadBaseControl instance for PropertyT

---

hedgehog/src/Hedgehog/Internal/Gen.hs

Assuming the instances work as expected, this **should** fix #287 
I'm fairly sure this is all possible thanks to #321 by @HuwCampbell.

MonadGen instances for StateT

---

hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Range.hs
hedgehog/src/Hedgehog/Internal/State.hs

- Some cases of `/.../` spread across lines
- One case of `\ -> ...` needing another backslash.
- Fix one typo (Symmbolic -> Symbolic)
- Add `/.../` formatting for consistency: This appears to be the style.

Fix some formatting bugs in Haddock

---

README.md

It ought to be parsed automatically but it's not. (https://github.com/hedgehogqa/haskell-hedgehog/issues/72)

Bump hackage badge version

---

hedgehog/src/Hedgehog/Internal/Range.hs

There is probably more we can do to address #38, but immediately I think that just mentioning that the bounds of `Size` are 0 and 99 is a good start.

Some doc on the bounds of Size (#38)

---

hedgehog/src/Hedgehog/Internal/Range.hs
hedgehog/src/Hedgehog/Internal/Tree.hs

Using `Data.List.inits` to produce the initial segments saves
quite a bit of time.

Reimplement splits

---

hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Gen.hs

* Add `shuffleSeq` to shuffle sequences.
* Use `shuffleSeq` to implement `shuffle` much more efficiently. The shuffling
algorithm we use finds and removes an arbitrary element, which sequences
can do in logarithmic time and space rather than linear time and
space. It also uses `length`, which is constant time for sequences and
linear time for lists.
* Bump lower bound on `containers`. We could avoid this, if necessary,
by not using pattern synonyms for sequences.

Speed up shuffle

---

hedgehog/src/Hedgehog/Internal/Gen.hs

Avoid pattern matching variables and use if expressions over guards, as per [STYLE_GUIDE](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/STYLE_GUIDE.md) and https://github.com/hedgehogqa/haskell-hedgehog/commit/ecad248f239ddccbbfbe4889b4c2f89851ae2141.

Clean up shuffleSeq

---

hedgehog/src/Hedgehog/Gen.hs

As discussed with @jacobstanley and as commented earlier at https://github.com/hedgehogqa/haskell-hedgehog/commit/ecad248f239ddccbbfbe4889b4c2f89851ae2141.

Make `shuffleSeq` accessible via `Hedgehog.Internal.Gen`

---

hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

..by not autodetecting `UseColor` on every `updateSummary` if it is not provided.
`detectColor` is expensive because it calls `hSupportsANSI`, which can result in lookup of 3 environment variables and a call to `IODevice.isTerminal`.
This commit replaces several cases of `Maybe UseColor` with `UseColor` and detects/resolves color explicitly in `check`, `recheck` and `checkGroup`.
See [my earlier comment](https://github.com/hedgehogqa/haskell-hedgehog/pull/240#issuecomment-549049191) for performance numbers I collected while testing.

Fix performance issues with color handling

---

hedgehog/src/Hedgehog/Internal/Gen.hs

Not sure why these weren't implemented.
These aren't the most commonly used functions, but `undefined` is worth removing nonetheless.

Remove `undefined` in GenT's MonadWriter instance

---

hedgehog/src/Hedgehog/Internal/Tree.hs

The version of `interleave` before this PR was closely modelled on my
blog post; a tiny bit _too_ closely; it wasn't the intention of the blog
post to define "good" shrinkers. I had a footnote for that but should
have made it a bit more prominent. Anyway, in this PR I change
`interleave` from being linear (removing one element at a time) to
logarithmic (trying to remove as big a chunk as possible at a time,
trying the whole list, half the list, etc.), matching the behaviour of
QuickCheck's `shrinkList`. This can have rather dramatic consequences
for the performance of shrinking.

Make `interleave` logarithmtic rather than linear

---

hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs

Bumping can break other peoples cabal, it's the unfortunate problem that [`containers` ships with GHC itself]( https://gitlab.haskell.org/ghc/ghc/wikis/commentary/libraries/version-history). — Merge with care.

Bump `containers` to `>= 0.5.8` simplifying `shuffleSeq`

---

hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs

This reverts commit e8d77d5c9e7ea3ed167529e2e44cb9133dfc5d44.
Turns out GHC 8.0.2 only has `containers-0.5.7.1`, would rather keep compat as long as possible, don't mind the little bit of CPP here if it buys us that.

Revert "Bump `containers` to `>= 0.5.8` simplifying `shuffleSeq` (#352)"

---

hedgehog-corpus/hedgehog-corpus.cabal

So that it matches the format we use in all the other places.

Format hedgehog-corpus.cabal

---

hedgehog-test-laws/test/test.hs

Or there's a valid reason to keep those? @jacobstanley

Remove testGroup "GenT" from hedgehog-test-laws since we skip it

---

hedgehog-test-laws/test/test.hs

As per the docs, [`monad` also contains these properties](http://hackage.haskell.org/package/checkers-0.5.0/docs/Test-QuickCheck-Classes.html#v:monadApplicative).

Remove monadApplicative from hedgehog-test-laws

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/src/Test/Example/QuasiShow.hs
hedgehog/hedgehog.cabal

I have bumped the bounds and updated the hedgehog-example:
```
┏━━ hedgehog-example/src/Test/Example/QuasiShow.hs ━━━
35 ┃ prop_foo :: Property
36 ┃ prop_foo =
37 ┃   property $ do
38 ┃     x <- forAll (SomeData <$> genFoo <*> genFoo)
┃     │ SomeData { someFoo1 = [foo|kick|] , someFoo2 = [foo|kick|] }
39 ┃     x === SomeData (Foo "quasi") (Foo "quoted")
┃     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
┃     │ ━━━ Failed (- lhs) (+ rhs) ━━━
┃     │ - SomeData { someFoo1 = [foo|kick|] , someFoo2 = [foo|kick|] }
┃     │ + SomeData { someFoo1 = [foo|quasi|] , someFoo2 = [foo|quoted|] }
```
I updated the bounds on Hackage for `hedgehog-1.0.2` already.
This will be particularly useful for types like dates and times which have a sensible human readable representation.
By changing the `Show` …

Bump pretty-show to 1.10 which supports quasi-quotes

---

hedgehog/src/Hedgehog/Gen.hs

Allows the functionality these represent to be used when the GenBase m
is not Identity.

Add filterT, justT, and mapMaybeT to Gen exports.

---

hedgehog/src/Hedgehog/Internal/Gen.hs

This PR adds the `either` generator suggested by @chessai in #245, and also an unbiased `either_` version.
Regarding documentation: I grouped these generators in the same section as the `maybe` generator, but I'm not too sure about it being under "Collections". What do the maintainers think?

Add either and either_

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/src/Test/Example/EvalNF.hs
hedgehog-example/test/test.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Property.hs

Added `evalNF` as discussed in #383.
A couple of things:
1. I created a local `failException'`, which behaves exactly like `failException` except it also prints `━━━ Value could not be evaluated to normal form ━━━`. Alternatively, we could simply change the type of `failException` to take an additional list of lines to be printed.
```haskell
-- before
failException :: (MonadTest m, HasCallStack) => SomeException -> m a
-- after
failException :: (MonadTest m, HasCallStack) => [String] -> SomeException -> m a
```
I suppose since `failException` is internal this would not be a breaking change, but still inconvenient... Any thoughts on whether we should refactor `failException` or leave the local bind for `failException'` in?
2. It wasn't clear to me how to add new tests for `evalNF`. I tried …

Add evalNF

---

hedgehog/hedgehog.cabal

I'm not sure if there was an announcement for it, but it appears that Hackage now rejects packages with cabal-version lower bound less than 1.10:
```
'cabal-version' must be at least 1.10
```
And because of 1.10 it's also required to add the `default-language` field.

Bump cabal-version lower bound

---

hedgehog/hedgehog.cabal

Since we have dropped support for GHC 7.10, the redundant packages `fail` and `semigroups` can be removed now. The additional warning is also included in `-Wall`.

Clean up hedgehog.cabal for GHC 8.0+

---

hedgehog/src/Hedgehog/Internal/Range.hs

`scaleLinear` currently only allows the largest value to be generated when at the maximum size `99`:
```
> fmap (\sz -> scaleLinea sz 0 4) [0..99] :: [Integer]
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2
,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4]
```
This improves the distribution so each value is the `max` for an equal number of sizes:
```
> fmap (\sz -> scaleLinear sz 0 4) [0..99] :: [Integer]
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4]
```

Improve the distribution of `scaleLinear`

---

hedgehog/src/Hedgehog/Internal/Gen.hs

Change frequency generator immediately shrink
The frequency generators works by totalling all weights, and then
picking a random number between [0, total]. It then selects the first
generator who's cummulative weight matches this number. This works fine,
but the current implementation leads to poor shrinking behavior. In
particular, the shrinking is driven by repeatedly picking smaller
numbers in the range [0, total]. For skewed distributions, this can mean
repeatedly reselecting the same generator.
This commit makes the observation that the weight only matters for the
first pick. Once you have made a choice and observed a test failure, you
can give all generators equal weight, as we're going to perform a
breadth-first enumeration to try and find a shrink anyway.
Before this patch, we …

Change frequency generator to immediately shrink

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs

adds:
```haskell
evalMaybe :: (MonadTest m, Show a, HasCallStack) => Maybe a -> m a
evalMaybeM :: (MonadTest m, Show a, MonadCatch m, HasCallStack) => m (Maybe a) -> m a
evalEitherM :: (MonadTest m, Show x, MonadCatch m, HasCallStack) => m (Either x a) -> m a
```
Fixes #368

Add evalMaybe, evalMaybeM and evalEitherM

---

hedgehog-dieharder/hedgehog-dieharder.cabal
hedgehog/hedgehog.cabal

Tested with the following config:
```
packages:
hedgehog
hedgehog-corpus
hedgehog-dieharder
hedgehog-example
hedgehog-quickcheck
hedgehog-test-laws
-- would like to do this but cabal applies it to
-- _all_ packages not just local :wtf:
--    https://github.com/haskell/cabal/issues/3883
-- program-options
--   ghc-options: -Wall -Werror
package hedgehog
ghc-options: -Wall -Werror
package hedgehog-corpus
ghc-options: -Wall -Werror
package hedgehog-dieharder
ghc-options: -Wall -Werror
package hedgehog-example
ghc-options: -Wall -Werror
package hedgehog-quickcheck
ghc-options: -Wall -Werror
package hedgehog-test-laws
ghc-options: -Wall -Werror
tests: True
constraints:
bytestring >= 0.11
allow-newer:
-- https://github.com/tibbe/hashable/pull/191
hashable:bytestring,
-- …
```

Allow bytestring-0.11

---

hedgehog/src/Hedgehog/Internal/Shrink.hs

This fixes the odd situation in which 2 is not representable as a number in a type. In particular this occurs in the package 'clash-prelude', which defines types such as `Unsigned 1` where only 0 and 1 can be represented.
This is in a sense more of an issue with `clash` types not having fully valid `Num` instances, however it is very easy to fix here and having an error during shrinking is very difficult to debug!

Use Integer in towards for halving during shrinking

---

hedgehog/src/Hedgehog/Internal/Gen.hs

The current shrink strategy produces potentially quite a lot of
duplication. By using a binary search, we should be able to
significantly speed up shrinking.
With this change we can see
```
Gen.printTreeWith  30 (Seed 5 3)  $ Gen.int (Range.constant 0 22)
7
├╼ 0
├╼ 4
│  ├╼ 2
│  │  └╼ 1
│  └╼ 3
└╼ 6
└╼ 5
```
While before we had
```
Gen.printTreeWith  30 (Seed 5 3)  $ Gen.int (Range.constant 0 22)
7
├╼ 0
├╼ 4
│  ├╼ 0
│  ├╼ 2
│  │  ├╼ 0
│  │  └╼ 1
│  │     └╼ 0
│  └╼ 3
│     ├╼ 0
│     └╼ 2
│        ├╼ 0
│        └╼ 1
│           └╼ 0
└╼ 6
├╼ 0
├╼ 3
│  ├╼ 0
│  └╼ 2
│     ├╼ 0
│     └╼ 1
│        └╼ 0
└╼ 5
├╼ 0
├╼ 3
│  ├╼ 0
│  └╼ 2
│     ├╼ 0
│     └╼ 1
│        └╼ 0
└╼ 4
├╼ 0
├╼ 2
│  ├╼ 0
│  └╼ 1
│     └╼ 0
└╼ 3
├╼ 0
└╼ 2
├╼ 0
└╼ 1
└╼ 0
```
The first level of the tree is exactly the same, …

Use binary shrinking for integral.

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Distributive.hs
hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/State.hs
hedgehog/src/Hedgehog/Internal/TH.hs

This PR makes Hedgehog compile with the current GHC development branch (soon to be GHC 9). It only required two minor changes on hedgehog side:
* Use `Data.Kind.Type` instead of `*`
* Supporting template-haskell 2.17
See the commit messages for a bit more details.
These changes should be enough from the hedgehog side, but even after these:
* `--allow-newer` flag has to be passed since `primitive` has an overly restrictive upper bound on `base`.
* `QuickCheck` does not compile [yet](https://github.com/nick8325/quickcheck/pull/311), so `hedgehog-quickcheck` does not work yet.
I tried to keep the changes as small as possible while maintaining the backwards compatibility, however I did only check with GHC 8.10 and GHC 9. Let me know if there is anything else I should do to get it compatible …

GHC 9 Support

---

hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/State.hs

While the contents of the action is fair game for shrinking, as is the sequence of actions, it makes little sense to change an action which may be the one which causes the error.

Don't shrink the action chosen in state machine testing

---

hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Tree.hs

This is just a minor cleanup, there should be no function differences.
As I mentioned earlier, my original version wrapped and unwrapped trees a bit much, making the code a bit harder to follow.
Pulling out a helper for `integral_` means we can build on values only.

Build tree from values instead of wrapping and unwrapping

---

CHANGELOG.md
hedgehog/hedgehog.cabal

Worth noting that this release comes with #392 which supports GHC 9 (fixes #416)
It has been uploaded to Hackage: [hedgehog-1.0.5](https://hackage.haskell.org/package/hedgehog-1.0.5)
/cc @vrom911

Release 1.0.5

---

hedgehog-example/src/Test/Example/Registry.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Barbie.hs
hedgehog/src/Hedgehog/Internal/HTraversable.hs

Added an example showing how to derive `TraversableB` and a warning if you try to use `HTraversable`.
Hopefully that makes the upgrade process a bit easier.
Any suggestions welcome.

Add better TraversableB documentation including deprecation warning for HTraversable

---

hedgehog-quickcheck/src/Test/QuickCheck/Hedgehog.hs

We can be more generous to folks with QuickCheck tests by allowing them to use hedgehog generators directly in their properties without sacrificing shrinking.
This is pretty explicity derived from @jacobstanley's code and QuickChecks's `forAll`.
I've run a bad example to show that it works fine with discards and predicates.
```
> let gInt = Gen.int (Range.constant 0 22)
> quickCheck $ Test.QuickCheck.Hedgehog.forAll (gInt >>= \i -> if even i then pure i else Gen.discard ) $ \x -> True Test.QuickCheck.=== (x < 18)
*** Failed! Falsified (after 2 tests and 2 shrinks):    
18
True /= False
```

Support shrinking with hedgehog generators in QuickCheck

---

.github/workflows/ci.yaml
hedgehog-example/hedgehog-example.cabal
hedgehog-example/src/Test/Example/References.hs
hedgehog-example/src/Test/Example/Registry.hs
hedgehog-example/src/Test/Example/Resource.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Report.hs

Widens template-haskell bounds and removes `mappend` definitions in favor of defaulting to `<>`, as per `-Wnoncanonical-monoid-instances`.

Support GHC 9.2.

---

hedgehog/src/Hedgehog/Internal/Property.hs

This is a minor thing :smile:  but I was totally confused for few minutes after staring at this example in haddocks (notice how True and False are rendered - but the 2nd argument of Cover is `LabelName`)
This might be some haddock bug - it renders `String` literals in other code blocks correctly, but for some reason it renders True and False in this case as (dead) links.
After this small fix the example is rendered correctly (tested locally):

Tweak 'cover' example code in haddocks

---

hedgehog/src/Hedgehog/Internal/Config.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/Seed.hs

I wasn't able to push to #424's branch so this is a rebase to check the build.
*edit: The 9.2 build found that a call to `read` resulted in a non-exhaustive pattern match so I have fixed that. Note that this means we now fail silently if `HEDGEHOG_SEED` can't be parsed. This is inline with how we handle the other environment variables which maybe isn't the best thing but is consistent at least. 😓*

Apply patch for fixed seed with minor modifications. (updated)

---

hedgehog/src/Hedgehog/Internal/Gen.hs

I thought an example on `Gen.subsequence` might be helpful to clarify that:
- Subsequences don't have to be contiguous
- Elements in the subsequence retain their ordering from the original sequence, and don't get shuffled around
- Subsequences shrink toward `[]` rather than toward the original list

Add example for Gen.subsequence

---

hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Gen.hs

Add Gen.subset

---

.github/workflows/ci.yaml
hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal

Tested using
cabal test --constraint='text>=2' all -w ghc-9.2.1
Fixes #443.
The test failures of old GHC versions on Windows are compiler bugs, it seems: haskell/text/pull/404

Compatibility with text-2.0

---

hedgehog-example/hedgehog-example.cabal
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog/hedgehog.cabal

Tested with the following addition to `cabal.project` (to fix `happy`):
```
source-repository-package
type: git
location: git@github.com:haskell/happy.git
tag: cc0fc789a19b9c3bdb1b1ed29bf910f386cefdf7
subdir: packages/tabular
source-repository-package
type: git
location: git@github.com:haskell/happy.git
tag: cc0fc789a19b9c3bdb1b1ed29bf910f386cefdf7
subdir: packages/grammar
```
And the following command line:
cabal test all --constraint='mtl>=2.3' --constraint='transformers>=0.6' --constraint='mmorph>=1.2'
All test pass.
I don't think the happy override should be committed since it will be unnecessary soon when haskell/happy#236 is closed.
This follows up on bumps missed in #427 and #449.

Allow newer dependencies

---

hedgehog/src/Hedgehog/Internal/State.hs

Closes #448. Suppose we have an Action list
A 1 -> Var 0
B (Var 0) -> ...
Then when we shrink A, we would previously get the list
A 0 -> Var 1
B (Var 0) -> ...
And then we'd drop B from this list, because `Var 0` no longer exists.
Now shrinking will give
A 0 -> Var 0
B (Var 0) -> ...
which is fine.
This means we now generate Vars even for actions whose `Require` fails.
I don't know if this is the ideal way to fix this. I wonder whether, when shrinking, the context should be rolled back so that the output we previously generated is no longer present? But I wouldn't know how to change that, and I'd be much less confident of not breaking anything else if I did.

Don't drop actions depending on shrunk predecessors.

---

.github/workflows/ci.yaml
hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs

This allows compatibility with GHC 9.4. Tested with `cabal test -w ghc-9.4.1`.
The extension is added because of this new warning:
```
src/Hedgehog/Internal/Gen.hs:312:46: error: [-Wtype-equality-requires-operators, -Werror=type-equality-requires-operators]
The use of ‘~’ without TypeOperators
will become an error in a future GHC release.
Suggested fix: Perhaps you intended to use TypeOperators
|
312 | toTree :: forall m a. (MonadGen m, GenBase m ~ Identity) => m a -> m (Tree a)
```

GHC 9.4 compatibility

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Config.hs
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/test/Test/Hedgehog/Skip.hs
hedgehog/test/test.hs

This won't be good to merge as-is, but if the feature is desirable, I'd be happy to help get it ready, including making supporting PRs to other repositories. (hspec-hedgehog will need one, and support for the feature in hspec would be nice.)
Using environment variables, this lets the user either
* `HEDGEHOG_SKIP_TO_TEST`: Start testing at a specific test number, and then continue from there. If it fails it'll shrink, if it passes it'll move on to the next test. Or,
* `HEDGEHOG_SKIP_TO_SHRINK`: Test at a specific test number and shrink state. If it fails it won't shrink further, if it passes the test will pass. The shrink state is encoded as an alphanumeric string and printed below the test and shrink counts.
Caveat: I don't think it's possible to walk the shrink tree without running tests …

Allow skipping to a specific test number or shrink result

---

hedgehog/src/Hedgehog/Internal/Property.hs

In [`tasty-hedgehog`](https://github.com/qfpl/tasty-hedgehog), we run `hedgehog` properties one-at-a-time rather than in (Hedgehog) groups. This means that the `TestCount` component of the new `Skip` type is fairly useless to us. See my discussion in https://github.com/qfpl/tasty-hedgehog/issues/61#issuecomment-1222314322. However, the `ShrinkPath` component _is_ useful. It would therefore be nice to have access to the `shrinkPathCompress` and `shrinkPathDecompress` functions, but they are not currently exported by the `Hedgehog.Internal.Property`. This PR changes this so that they are exported and also adds some documentation for them.

Export `shrinkPathCompress` and `shrinkPathDecompress`

---

.github/workflows/ci.yaml

GHC 8.0, 8.2 and 8.4 failed because these old GHC versions ship a buggy Haddock. I added a predicate to skip Haddock generation on these old versions. Also bumped all other bounds old versions I could find.
See 
* https://github.com/haskell/text/issues/514

Update Github CI actions, exclude Haddocks for old GHCs

---

hedgehog/src/Hedgehog/Internal/Gen.hs

Having this only work on lists is more restrictive than it needs to be. This commit generalizes `element` to instead work on any `Foldable`.

Generalise Hedgehog.Gen.element

---

CHANGELOG.md
hedgehog/src/Hedgehog/Internal/Seed.hs

This e.g. allows you to control the output of `sample` when writing documentation / doctests.

Export Hedgehog.Internal.Seed.seed

---

hedgehog/src/Hedgehog/Internal/Gen.hs
hedgehog/src/Hedgehog/Internal/Tree.hs

`prune`'s documentation was incorrect. `filter`'s was at best misleading, and in any case not detailed enough for me to avoid pitfalls (#484). The others were missing entirely.

Improve docs: `Gen.filter[T]`, `Gen.mapMaybe[T]`, `Tree.prune`.

---

hedgehog/src/Hedgehog/Internal/State.hs

Looks like this comment was missed in the `HTraversable`->`barbies` migration.

State: Remove HTraversable from haddock

---

CHANGELOG.md
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/test/Test/Hedgehog/Skip.hs

Closes #487.
In #454 we introduced test skipping, with the idea that a failed test could report a way for you to jump back to reproduce it without all the preceding tests.
But it didn't work if any of the preceding tests had been discarded, because each discard also changes the seed and the size. Users could manually add the discard count to the test count in the `Skip`, but that's no fun. Plus, it wouldn't work if the test count plus discard count exceeded the test limit, because that would generate a success without running any tests.
So now a `Skip` (other than `SkipNothing`) includes a `DiscardCount` as well as a `TestCount`. It's rendered in the compressed path as `testCount/discardCount`, or just `testCount` if `discardCount` is 0. The exact sequence of passing tests and discards …

Fix test skipping when tests have been discarded.

---

.github/workflows/ci.yaml
cabal.project
hedgehog-dieharder/hedgehog-dieharder.cabal
hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal

Fixed version of https://github.com/hedgehogqa/haskell-hedgehog/pull/503
Thanks to @ysangkok for most of the work here!

Allow GHC 9.8

---

hedgehog/hedgehog.cabal

Relax upper bound on `ansi-terminal` to permit `ansi-terminal-1.1`.
This resolves https://github.com/hedgehogqa/haskell-hedgehog/issues/511 by @mpilgrem.

Relax upper bound on `ansi-terminal`

---

hedgehog/src/Hedgehog/Internal/Report.hs

Currently `hedgehog` error output is literally useless when used with `hspec-hedgehog`.
`hedgehog` includes the whole top-level definition in which the error occurred in the error output. Hspec test suites  tend to define all tests in one top level definition. As a result, `hspec-hedgehog` will include the whole test suite in the error output for each failing test.
This produces lots of boring output with only little  interesting  output in between.
This PR allows the user to specify an upper limit of boring output lines that are printed around interesting output lines. This can be used by `hspec-hedgehog` to provide more useful error output.
https://github.com/hspec/hspec-hedgehog/pull/35

Show less context on failure

---

hedgehog/src/Hedgehog/Internal/Report.hs

This is not useful in the context of `hspec-hedgehog`.  Hspec uses its global seed when running hedgehog properties and it already prints instruction on how to re-run with the same seed when a test fails.

renderResultWith: Allow to disable the `recheckAt`-message

---

hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

- Fix a typo
- Remove redundant `TestCount`

Fix "insufficient coverage" message

---

hedgehog/src/Hedgehog/Internal/Report.hs

This is part of https://github.com/hedgehogqa/haskell-hedgehog/issues/522.

Allow to omit icons at the start of important output lines

---

hedgehog-example/hedgehog-example.cabal
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog-test-laws/hedgehog-test-laws.cabal

We have an `allow-newer: hedgehog-quickcheck:QuickCheck` working internally, and this PR passed `cabal test all --constraint 'QuickCheck ^>=2.15'`.
Can we please also get metadata revisions on Hackage?

hedgehog-{example,quickcheck,test-laws}: Raise QuickCheck bound

---

.github/workflows/ci.yaml
hedgehog-example/hedgehog-example.cabal
hedgehog-test-laws/hedgehog-test-laws.cabal
hedgehog-test-laws/test/test.hs
hedgehog/hedgehog.cabal

Tested on Linux with GHC versions `8.10.7`, `9.6.5`, `9.8.2` and `9.10.1`

Make it build with ghc 9.10

---

CHANGELOG.md
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog/hedgehog.cabal

@sol, @endgame, @erikd, @JackKelly-Bellroy, @jchia, @moodmosaic, @ocharles, @tomjaguarpaw, @Vekhir

Release 1.5

---

.github/workflows/ci.yaml
CHANGELOG.md
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Gen.hs

Previously, `val <- Gen.element []` would give an error like
Hedgehog.Gen.element: used with empty Foldable
CallStack (from HasCallStack):
error, called at src/Hedgehog/Internal/Gen.hs:1197:5 in hedgehog-1.4-FEcjASqhnyiHkb8BJanjYM:Hedgehog.Internal.Gen
Which isn't very helpful. Now the callstack entry points to my own code, instead.
I guess this will need a version bump since it changes types?
I think I got all the generators that are expected to throw errors. Some call `error` but describe it as internal, and I didn't touch those.

Add callstacks to generators that can error.

---

hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal

Bump upper bounds for containers to < 0.9 and random to < 1.4.
Resolves https://github.com/hedgehogqa/haskell-hedgehog/issues/542, https://github.com/hedgehogqa/haskell-hedgehog/issues/543.

Bump upper bounds for containers and random

---

CHANGELOG.md
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog/hedgehog.cabal

See https://github.com/hedgehogqa/haskell-hedgehog/pull/554#issuecomment-3287624883 for the reason I bumped to 1.7 instead of 1.6.1.
/cc @tomjaguarpaw @HuwCampbell

Release 1.7
