src/Hedgehog/Example.hs
src/Hedgehog/Internal/Report.hs
src/Hedgehog/Internal/Source.hs
src/Hedgehog/Runner.hs

The inline output works out pretty well for this example:

Hutton's razor example

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Gen.hs
hedgehog/src/Hedgehog/Internal/Tree.hs
hedgehog/src/Hedgehog/Property.hs

Implement mtl + other common monad type classes

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/test/Test/Example/STLC.hs

This could use a fair bit of cleaning up, but is mostly there. The generators are working reasonably well, though they may not be idiomatic. `genWellTypedApp` is producing reasonably interesting chains of function application.
As you can see, I haven't bothered implementing `subst`, should probably do that.
@jystic @charleso

WIP STLC example

---

hedgehog-example/hedgehog-example.cabal
hedgehog-example/test/Test/Example/Basic.hs
hedgehog-example/test/Test/Example/STLC.hs
hedgehog-example/test/test.hs
hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Property.hs
hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs
hedgehog/src/Hedgehog/Internal/Show.hs

Not sure if the look/feel is quite right yet, but it's a start

Add diffs when using the === operator

---

hedgehog/src/Hedgehog/Internal/Report.hs
hedgehog/src/Hedgehog/Internal/Runner.hs

I've also exposed the constructors for the limits, after having a think about it I think there's no benefit to hiding them as far as I can see.
This fixes https://github.com/hedgehogqa/haskell-hedgehog/issues/30
/cc @erikd @dalaing

Split Status data type in to Progress + Result

---

hedgehog/hedgehog.cabal
hedgehog/src/Hedgehog/Internal/Report.hs

This is partially for amusement value 😆 (but in all seriousness, it's also so I can keep the default as displaying with colour)

Keep the boss happy

---

README.md

Just bringing the readme up to date with reality

Fix readme (checkConcurrent -> checkParallel)

---

CHANGELOG.md
README.md
hedgehog/hedgehog.cabal

The state machine stuff is still a bit experimental, but we'll never get it solid if we don't use it, time for a release! 🔥

Release 0.4

---

CHANGELOG.md

See discussion around [here](https://github.com/hedgehogqa/haskell-hedgehog/pull/86#issuecomment-307601464).

Add reference-style markdown links

---

hedgehog/src/Hedgehog/Internal/Property.hs

This seemed to be the consensus for resolving issue #121.

Add doc explaining use of "withTests 1"

---

hedgehog/src/Hedgehog/Internal/Report.hs

This may or may not entirely solve #141, but it is a good idea to have either way.
Edit: Remove my usage of "fix" github keyword.

Explicitly define Semigroup instance for Summary

---

CHANGELOG.md
hedgehog/hedgehog.cabal

Thanks to all the contributors!

Release 0.5.3

---

hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal

Forgot about this one, will update hackage with a revision to match this.

Bump upper bounds for pretty-show

---

CHANGELOG.md
hedgehog/hedgehog.cabal

Release 0.6

---

hedgehog-quickcheck/hedgehog-quickcheck.cabal

Was bound to happen, wow what a terrible pun i'm sorry

Widen bounds for hedgehog-quickcheck

---

hedgehog/src/Hedgehog.hs

This replaces PR #206 as I could not re-open it. As requested by @moodmosaic.

Expose forAllT and forAllWithT

---

hedgehog/src/Hedgehog/Internal/Tripping.hs

Add example for tripping

---

.appveyor.yml
hedgehog/src/Hedgehog/Internal/Runner.hs

This was removed in https://github.com/hedgehogqa/haskell-hedgehog/pull/271/commits/43d7e272b4f46f11a177f494cb6202066bbca556#diff-724bc13f92f28d11e3df4525f10ed86a but it shouldn't.

Fix broken build on Windows/MinGW

---

.travis.yml
bors.toml

Hiya :wave: !
Had a chat with @jystic about bringing on bors for in-work Rust port of hedgehog over at  https://github.com/justanotherdot/rust-hedgehog. Seems like integrating it was surprisingly simple and this is the followup PR for integrating it upstream.

Use bors on pull requests

---

CHANGELOG.md
README.md
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog/hedgehog.cabal

Release 1.0

---

hedgehog-quickcheck/hedgehog-quickcheck.cabal

Forgot to merge this, uploaded to hackage last week

hedgehog-quickcheck-0.1.1

---

hedgehog/src/Hedgehog.hs
hedgehog/src/Hedgehog/Internal/Property.hs

Export LabelName from main module

---

hedgehog/hedgehog.cabal

Resolves #302 
---
/cc @jacobstanley @gwils @chshersh

Bump primitive version bound

---

hedgehog/src/Hedgehog/Internal/Distributive.hs

Simplify distributeT

---

hedgehog/src/Hedgehog/Internal/Distributive.hs
hedgehog/src/Hedgehog/Internal/Source.hs
hedgehog/src/Hedgehog/Internal/State.hs
hedgehog/src/Hedgehog/Internal/Tree.hs
hedgehog/src/Hedgehog/Main.hs

Those aren't seem to be used. I'm curious to see if CI(s) will pick up anything weird.

Remove unused {-# LANGUAGE CPP #-}

---

cabal.project
hedgehog-corpus/LICENSE
hedgehog-corpus/README.md
hedgehog-corpus/hedgehog-corpus.cabal
hedgehog-corpus/src/Hedgehog/Corpus.hs

Moving this from https://github.com/tmcgilchrist/hedgehog-corpus

Import hedgehog-corpus

---

hedgehog/src/Hedgehog/Internal/Report.hs

There are two possible ways which a source can't be printed at a location; the location isn't known, or we can't find the source.
In either of these we should fall back to reporting it simply, while previously, if the source file couldn't be found we would simply skip the error message.
I thought about using a `MaybeT` to skip a case analysis; but this seems simple enough to not worry about it.
Fixes #379 
Fixes #386.

Don't swallow errors if we can't find the source file

---

hedgehog/src/Hedgehog/Internal/Property.hs

- Change `where` to `let` (STYLE_GUIDE.md)

Housekeeping

---

CHANGELOG.md
hedgehog/hedgehog.cabal

https://github.com/hedgehogqa/haskell-hedgehog/compare/1.0.2..5d1afd855d05cfffed17fe29441905acbc4f8e6a

Release 1.0.3

---

hedgehog/hedgehog.cabal

See https://github.com/commercialhaskell/stackage/issues/5592

Allow ansi-terminal-0.11

---

hedgehog-test-laws/hedgehog-test-laws.cabal
hedgehog/hedgehog.cabal

Builds fine and all tests pass here.

Allow random 1.2

---

CHANGELOG.md
hedgehog/hedgehog.cabal

https://github.com/hedgehogqa/haskell-hedgehog/compare/1.0.3...27aad87c01a5179e657abd8e3c691952d51ba1c0

Release 1.0.4

---

hedgehog/hedgehog.cabal

Bump time upper bound version

---

hedgehog/hedgehog.cabal

Builds fine and all tests pass.

Allow mmorph 1.2

---

CHANGELOG.md

Note that this was a new point release on the previous major version.
For more info see: https://github.com/qfpl/tasty-hedgehog/issues/61#issuecomment-1234009175

Include Version 1.1.2 in CHANGELOG.md

---

hedgehog-example/hedgehog-example.cabal
hedgehog/hedgehog.cabal

Would be great to get new releases/revisions with this change.

Bump upper bounds for resourcet and primitive.

---

hedgehog/hedgehog.cabal

@moodmosaic 
Builds and tests fine. Closes #508

Support primitive 0.9

---

hedgehog/hedgehog.cabal

Fixes https://github.com/hedgehogqa/haskell-hedgehog/issues/512

Relax time dependency to < 1.15

---

hedgehog/src/Hedgehog/Internal/Property.hs

Wrap `evalMaybeM` and `evalEitherM` in `withFrozenCallStack`

---

hedgehog/src/Hedgehog/Internal/Report.hs

This is part of https://github.com/hedgehogqa/haskell-hedgehog/issues/522.

Allow to omit source location from report

---

hedgehog-example/hedgehog-example.cabal
hedgehog-quickcheck/hedgehog-quickcheck.cabal
hedgehog-test-laws/hedgehog-test-laws.cabal

Support QuickCheck-2.16

---

hedgehog/hedgehog.cabal

Builds fine and all tests pass.

Allow lifted-async 0.11
